### ISSUE TITLE
vector append exception during ldmx-sw tests

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#59]
**Describe the bug**
With the newer GCC, I am now seeing a funky exception during the ldmx-sw tests. Need to investigate further.

**To Reproduce**
1. compile ldmx-sw trunk
2. run `ctest` in the build directory

**Expected behavior**
We'd like ldmx-sw to pass its tests.

**What tag of the container are you using?**

`v4.0.0-rc0`

**What application are you using to run the container?**

The test application.

**Additional context**
https://github.com/LDMX-Software/docker/pull/58#issuecomment-1595785496

**Comment by tomeichlersmith** [comment]
Annoyingly, when I build with `CMAKE_BUILD_TYPE=Debug`, I get a different exception.
```
[ldmx] tom@iroh:~/ldmx/ldmx-sw/build/test$ ldmx ../run_test
Randomness seeded to: 2053282342
creating file
starting Read
creating file

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_test is a Catch2 v3.3.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Hcal Digi Pipeline test
-------------------------------------------------------------------------------
/home/tom/ldmx/ldmx-sw/Hcal/test/HcalDigiPipelineTest.cxx:332
...............................................................................

/home/tom/ldmx/ldmx-sw/Hcal/test/HcalDigiPipelineTest.cxx:332: FAILED:
due to unexpected exception with message:
  Python Object does not have __dict__ member and is not a dict.

Traceback (most recent call last):
  File "/home/tom/ldmx/ldmx-sw/build/test/hcal_geometry_test_config.py", line 4, in <module>
    p = ldmxcfg.Process( 'test_hcal_geometry' )
  File "/home/tom/ldmx/ldmx-sw/install/python/LDMX/Framework/ldmxcfg.py", line 377, in __init__
    raise Exception( "Process object is already created! You can only create one Process object in a script." )
Exception: Process object is already created! You can only create one Process object in a script.
-------------------------------------------------------------------------------
Hcal Geometry test
-------------------------------------------------------------------------------
/home/tom/ldmx/ldmx-sw/Hcal/test/HcalGeometryTest.cxx:118
...............................................................................

/home/tom/ldmx/ldmx-sw/Hcal/test/HcalGeometryTest.cxx:118: FAILED:
due to unexpected exception with message:
  Problem loading python script

===============================================================================
test cases:    10 |     8 passed | 2 failed
assertions: 19327 | 19325 passed | 2 failed

```

**Comment by tomeichlersmith** [comment]
The current error in debug mode is coming from an object in the conditionsObjectProviders list.
```
conditionsObjectProviders : list[object] 10                                                                                                                                                                
0 0x7ff2a3ff2950                                                                                                                                                                                           
 objectName : str                                                                                                                                                                                          
 className : str                                                                                                                                                                                           
 tagName : str                                                                                                                                                                                             
 seedMode : str                                                                                                                                                                                            
 seed : int                                                                                                                                                                                                
1 0x7ff2a4060850                                                                                     
 objectName : str                                                                                    
 className : str                                                                                     
 tagName : str                                                                                       
 dataType : str                                                                                      
 columns : list[str]                                                                                 
 entries : list[object] 1                                                                            
 0 0x7ff2a4062080                                                                                    
  URL : str                                                                                          
  firstRun : int                                                                                     
  lastRun : int                                                                                      
  runType : str                                                                                      
  values : list[int]                                                                                 
 conditions_baseURL : str                                                                            
 entriesURL : str                                                                                    
2 0x7ff2a4062110 
                         
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_test is a Catch2 v3.3.1 host application.
Run with -? for options
                                                  
-------------------------------------------------------------------------------
Hcal Digi Pipeline test
-------------------------------------------------------------------------------
/home/tom/ldmx/ldmx-sw/Hcal/test/HcalDigiPipelineTest.cxx:332
...............................................................................
                         
/home/tom/ldmx/ldmx-sw/Hcal/test/HcalDigiPipelineTest.cxx:332: FAILED:
due to unexpected exception with message:
  Python Object does not have __dict__ member and is not a dict.
```
I need to read the C API docs some more, there might be some function I need to call to load objects out of a memory-compressed state.

**Comment by tomeichlersmith** [comment]
I found a patch for the C API although I am still seeing a SIG ABORT error. Cracking out `gdb` shows that this is orginating from Geant4 when it can't find a data table to load into one of its physics tables. (not showing all the stumbling around I did to get to this point).
```

Breakpoint 1, G4SeltzerBergerModel::ReadData (this=0x55555570e570, Z=1, path=0x7fffffffe752 "/usr/local/share/geant4/data/G4EMLOW7.13") at /src/source/processes/electromagnetic/standard/src/G4SeltzerBergerModel.cc:147
147     /src/source/processes/electromagnetic/standard/src/G4SeltzerBergerModel.cc: No such file or directory.
(gdb) c
Continuing.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737309350848) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
```
This Geant4 code is asking for a different dataset version than what is installed in the container image.
```
eichl008@ldmx ~> ls /usr/local/share/geant4/data/
G4ABLA3.0    G4ENSDFSTATE1.2.3  G4NEUTRONXS1.4  G4SAIDDATA1.1         RadioactiveDecay4.3.2
G4EMLOW6.48  G4NDL4.5           G4PII1.3        PhotonEvaporation3.2  RealSurface1.0
```
sooo that's kinda funky

**Comment by tomeichlersmith** [comment]
The G4 not-found data comes from wrongly-defining the G4EMLOW data path:
```diff
diff --git a/Dockerfile b/Dockerfile
index d9181d6..cc0f723 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -236,7 +236,7 @@ RUN __owner="geant4" &&\
     cmake --build src/build --target install -j$NPROC &&\
     rm -rf src 
 ENV G4NEUTRONHPDATA="${G4DATADIR}/G4NDL4.6"
-ENV G4LEDATA="${G4DATADIR}/G4EMLOW7.13"
+ENV G4LEDATA="${G4DATADIR}/G4EMLOW6.48"
 ENV G4LEVELGAMMADATA="${G4DATADIR}/PhotonEvaporation5.7"
 ENV G4RADIOACTIVEDATA="${G4DATADIR}/RadioactiveDecay5.6"
 ENV G4PARTICLEXSDATA="${G4DATADIR}/G4PARTICLEXS3.1.1"
```

**Comment by tomeichlersmith** [comment]
I actually got a lot of the paths wrong... (from inside the image)...
```diff
[ldmx] eichl008@ldmx ~/ldmx-sw> env | grep G4
G4ENSDFSTATEDATA=/usr/local/share/geant4/data/G4ENSDFSTATE1.2.3
G4PIIDATA=/usr/local/share/geant4/data/G4PII1.3
G4INCLDATA=/usr/local/share/geant4/data/G4INCL1.0
G4LEDATA=/usr/local/share/geant4/data/G4EMLOW7.13
G4PARTICLEXSDATA=/usr/local/share/geant4/data/G4PARTICLEXS3.1.1
G4DATADIR=/usr/local/share/geant4/data
G4NEUTRONHPDATA=/usr/local/share/geant4/data/G4NDL4.6
G4SAIDXSDATA=/usr/local/share/geant4/data/G4SAIDDATA2.0
G4REALSURFACEDATA=/usr/local/share/geant4/data/RealSurface2.2
G4ABLADATA=/usr/local/share/geant4/data/G4ABLA3.1
G4LEVELGAMMADATA=/usr/local/share/geant4/data/PhotonEvaporation5.7
G4RADIOACTIVEDATA=/usr/local/share/geant4/data/RadioactiveDecay5.6
[ldmx] eichl008@ldmx ~/ldmx-sw> . geant4.sh
[ldmx] eichl008@ldmx ~/ldmx-sw> env | grep G4
G4ENSDFSTATEDATA=/usr/local/share/geant4/data/G4ENSDFSTATE1.2.3
G4PIIDATA=/usr/local/share/geant4/data/G4PII1.3
G4NEUTRONXSDATA=/usr/local/share/geant4/data/G4NEUTRONXS1.4
G4INCLDATA=/usr/local/share/geant4/data/G4INCL1.0
G4LEDATA=/usr/local/share/geant4/data/G4EMLOW6.48
G4PARTICLEXSDATA=/usr/local/share/geant4/data/G4PARTICLEXS3.1.1
G4DATADIR=/usr/local/share/geant4/data
G4NEUTRONHPDATA=/usr/local/share/geant4/data/G4NDL4.5
G4SAIDXSDATA=/usr/local/share/geant4/data/G4SAIDDATA1.1
G4REALSURFACEDATA=/usr/local/share/geant4/data/RealSurface1.0
G4ABLADATA=/usr/local/share/geant4/data/G4ABLA3.0
G4LEVELGAMMADATA=/usr/local/share/geant4/data/PhotonEvaporation3.2
G4RADIOACTIVEDATA=/usr/local/share/geant4/data/RadioactiveDecay4.3.2
```

**Comment by tomeichlersmith** [comment]
The vector append errors in Packing seem to be caused by some optimizations the newer compiler implements. Building with `CMAKE_BUILD_TYPE=RelWithDebInfo` is helpful in this case

```
(gdb) 
Continuing.

Program received signal SIGSEGV, Segmentation fault.
std::vector<packing::rawdatafile::SubsystemPacket, std::allocator<packing::rawdatafile::SubsystemPacket> >::_M_erase_at_end (__pos=0x5567664b5418, this=0x7fffffffbd68) at /usr/include/c++/11/bits/stl_vector.h:1796
1796                std::_Destroy(__pos, this->_M_impl._M_finish,
(gdb) bt
#0  std::vector<packing::rawdatafile::SubsystemPacket, std::allocator<packing::rawdatafile::SubsystemPacket> >::_M_erase_at_end (
    __pos=0x5567664b5418, this=0x7fffffffbd68) at /usr/include/c++/11/bits/stl_vector.h:1796
#1  std::vector<packing::rawdatafile::SubsystemPacket, std::allocator<packing::rawdatafile::SubsystemPacket> >::resize (
    __new_size=<optimized out>, this=0x7fffffffbd68) at /usr/include/c++/11/bits/stl_vector.h:942
#2  packing::utility::Reader::read<packing::rawdatafile::SubsystemPacket> (count=<optimized out>, 
    vec=std::vector of length 2, capacity 2 = {...}, this=0x7fffffffc290)
    at /export/scratch/users/eichl008/ldmx/ldmx-sw/Packing/include/Packing/Utility/Reader.h:174
#3  packing::rawdatafile::EventPacket::read (this=this@entry=0x7fffffffbd60, r=...)
    at /export/scratch/users/eichl008/ldmx/ldmx-sw/Packing/src/Packing/RawDataFile/EventPacket.cxx:46
#4  0x00005555555cbef8 in packing::utility::Reader::operator>><packing::rawdatafile::EventPacket, true> (o=..., this=0x7fffffffc290)
    at /export/scratch/users/eichl008/ldmx/ldmx-sw/Packing/include/Packing/Utility/Reader.h:153
#5  CATCH2_INTERNAL_TEST_0 () at /export/scratch/users/eichl008/ldmx/ldmx-sw/Packing/test/BinaryIO.cxx:109
#6  0x000055555565356c in Catch::TestInvokerAsFunction::invoke() const ()
#7  0x0000555555648271 in Catch::TestCaseHandle::invoke() const ()
#8  0x0000555555647362 in Catch::RunContext::invokeActiveTestCase() ()
#9  0x0000555555647076 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#10 0x0000555555645651 in Catch::RunContext::runTest(Catch::TestCaseHandle const&) ()
#11 0x00005555555f3a2b in Catch::(anonymous namespace)::TestGroup::execute() ()
#12 0x00005555555f4f30 in Catch::Session::runInternal() ()
#13 0x00005555555f4a32 in Catch::Session::run() ()
```

**Comment by tomeichlersmith** [comment]
Actually listening to the compiler warning fixes this issue :facepalm: 
```diff
diff --git a/Packing/src/Packing/RawDataFile/EventPacket.cxx b/Packing/src/Packing/RawDataFile/EventPacket.cxx
index 51a3d2e..b9c3b7c 100644
--- a/Packing/src/Packing/RawDataFile/EventPacket.cxx
+++ b/Packing/src/Packing/RawDataFile/EventPacket.cxx
@@ -46,6 +46,8 @@ utility::Reader& EventPacket::read(utility::Reader& r) {
   r.read(subsys_data_, num_subsys);
 
   r >> crc_;
+
+  return r;
 }
 
 utility::Writer& EventPacket::write(utility::Writer& w) const {
```

**Comment by EinarElen** [comment]
> The current error in debug mode is coming from an object in the conditionsObjectProviders list.
> ```
> conditionsObjectProviders : list[object] 10                                                                                                                                                                
> 0 0x7ff2a3ff2950                                                                                                                                                                                           
>  objectName : str                                                                                                                                                                                          
>  className : str                                                                                                                                                                                           
>  tagName : str                                                                                                                                                                                             
>  seedMode : str                                                                                                                                                                                            
>  seed : int                                                                                                                                                                                                
> 1 0x7ff2a4060850                                                                                     
>  objectName : str                                                                                    
>  className : str                                                                                     
>  tagName : str                                                                                       
>  dataType : str                                                                                      
>  columns : list[str]                                                                                 
>  entries : list[object] 1                                                                            
>  0 0x7ff2a4062080                                                                                    
>   URL : str                                                                                          
>   firstRun : int                                                                                     
>   lastRun : int                                                                                      
>   runType : str                                                                                      
>   values : list[int]                                                                                 
>  conditions_baseURL : str                                                                            
>  entriesURL : str                                                                                    
> 2 0x7ff2a4062110 
>                          
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> run_test is a Catch2 v3.3.1 host application.
> Run with -? for options
>                                                   
> -------------------------------------------------------------------------------
> Hcal Digi Pipeline test
> -------------------------------------------------------------------------------
> /home/tom/ldmx/ldmx-sw/Hcal/test/HcalDigiPipelineTest.cxx:332
> ...............................................................................
>                          
> /home/tom/ldmx/ldmx-sw/Hcal/test/HcalDigiPipelineTest.cxx:332: FAILED:
> due to unexpected exception with message:
>   Python Object does not have __dict__ member and is not a dict.
> ```
> I need to read the C API docs some more, there might be some function I need to call to load objects out of a memory-compressed state.

I see you also ran into the issue i had prompting https://github.com/LDMX-Software/Framework/issues/66 :)

Thanks for your quick work on patching all of these things
